### ISSUE TITLE
Climbing ignoring config

### ISSUE THREAD

**Issue by tomster12** [CammiePone/Gulliver-Reborn#10]
You cannot disable climbing blocks in the config.

After many hours of downloading old versions of java and figuring out gradle I found a single set of missing parenthesis in src/main/java/com/camellias/gulliverreborn/GulliverReborn.java

You were only checking the config and the player facing etc for dirt because of incorrect logic.

What it is:
			if(ClimbingHandler.canClimb(player, facing)
				&& Config.CLIMB_SOME_BLOCKS
				&& (block instanceof BlockDirt)
				|| (block instanceof BlockGrass)
				|| (block instanceof BlockMycelium)
				|| (block instanceof BlockLeaves)
				|| (block instanceof BlockSand)
				|| (block instanceof BlockSoulSand)
				|| (block instanceof BlockConcretePowder)
				|| (block instanceof BlockFarmland)
				|| (block instanceof BlockGrassPath)
				|| (block instanceof BlockGravel)
				|| (block instanceof BlockClay))

What it should be:
			if(ClimbingHandler.canClimb(player, facing)
				&& Config.CLIMB_SOME_BLOCKS
				&& ((block instanceof BlockDirt)
				|| (block instanceof BlockGrass)
				|| (block instanceof BlockMycelium)
				|| (block instanceof BlockLeaves)
				|| (block instanceof BlockSand)
				|| (block instanceof BlockSoulSand)
				|| (block instanceof BlockConcretePowder)
				|| (block instanceof BlockFarmland)
				|| (block instanceof BlockGrassPath)
				|| (block instanceof BlockGravel)
				|| (block instanceof BlockClay)))

**Comment by ModMCdl** [comment]
Have you confirmed this works? 

This mod no longer receives active support, but this is a quick enough fix to implement if that's the only issue.

**Comment by tomster12** [comment]
I made the change and built the mod again and its working for me now.
