### ISSUE TITLE
FOV when sprinting

### ISSUE THREAD

**Issue by OminousArchitect** [CammiePone/Gulliver-Reborn#2]
Hey I've noticed with this mod installed the FOV no longer changes when sprinting, I've tried both with and without Optifine, in case the "Dynamic FOV" option had some conflict with this mod, but no dice. The FOV just doesn't change at all when sprinting, period. After removing the mod the issue goes away so I can only assume this is the culprit.
(on another note thank you for remaking one of my favorite mods ever! Haven't seen this mod in years and thought it was truly dead)

**Comment by CammiePone** [comment]
Oh that's why it seemed wrong... yep, that's 100% my fault. I can fix that.

**Comment by OminousArchitect** [comment]
Nice! Glad to hear it. Thanks again for making this mod at all! Now my tiny house dreams from 1.6 can be realized again :D
