### ISSUE TITLE
Glitchy camera with other mods

### ISSUE THREAD

**Issue by Rickstery123** [CammiePone/Gulliver-Reborn#3]
I'm not sure entirely what mod is causing it, but whenver I change my size the camera gets really messed up and switches back and forth rapidly between heights, I believe it is more player models conflicting

**Comment by CammiePone** [comment]
You would be right, and it's something Noppes has to fix on their end. They've already informed me that the next release should include a fix to the config so that that doesn't happen when you disable the dynamic pov option.

**Comment by CJLee1299** [comment]
@Rickstery123 @CammiePone 
Hello, I've been looking around everywhere and can't find any solutions or pages/articles already posted about this, but when I host an LAN server with my friends I am not able to change my camera height using Gulliver Reborn, only with MPM with and without the Dynamic POV Enabled. If anyone has any idea what is going on or what I can do to fix this, I'd greatly appreciate any help.

**Comment by CammiePone** [comment]
@CJLee1299 
Yea that's because Noppes never pushed the fix and this mod is dead.
