### ISSUE TITLE
Small glitches noticed

### ISSUE THREAD

**Issue by BigBoyoBilly** [CammiePone/Gulliver-Reborn#4]
Some of the small bugs that I noticed in version 1.9, are that between the sizes 0.2 and 0.3 the smaller player models are stretched out and mounting players with a string if they are larger then you deals damage. These are the only two things that I really noticed while playing.

**Comment by CammiePone** [comment]
Hecc, I forgot to fix the crushing while mounted. My bad. Literally me having the entities swapped around in the check like an idiot ^^;

As for the stretching, that was because I'm an idiot and messed it up. Both are fixed now in my workspace.
