### ISSUE TITLE
command blocks

### ISSUE THREAD

**Issue by TGGTriston** [CammiePone/Gulliver-Reborn#5]
Does not work in command blocks.

**Comment by CammiePone** [comment]
Known issue, unknown fix

**Comment by DoomRater** [comment]
My players use command blocks to change player sizes.  @p works like a charm in our circumstance.

**Comment by TGGTriston** [comment]
Ah I can't seem to get it to work in my command blocks what forge are you
running and have you tried it in single player?

**Comment by DoomRater** [comment]
I tried running "/basesize @p .5" from a command block using Forge 14.23.5.2838 and Gulliver Reborn 1.8 in a single player world, and when I stepped on the pressure plate I was made smaller. To my knowledge, Gulliver Reborn 1.9 has not changed anything.

**Comment by DoomRater** [comment]
I appear to be mistaken.  1.9 is when some tab auto-completion features were added, and apparently something broke between my version and that version.  Most of the discussion about this has been on the Discord channel, so I figure I'd better relay it back to here.
