### ISSUE TITLE
Breaks Tinker's armory High Stride boots

### ISSUE THREAD

**Issue by florabean** [CammiePone/Gulliver-Reborn#6]
with this mod installed, even if my player hight is default the high stride modifier on my boots no longer works, at max level you can walk up 2.5 blocks but I can't even walk up one

**Comment by DoomRater** [comment]
I can confirm that both Thaumcraft's Boots of Travel and Botania's Sojourner's Sash still modify the player's step height, allowing even a teeny player to walk up a full block height.  I don't know if that will help pinpoint the issue here.
